import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow():
    def __init__(self):
        super().__init__()
        self.Mainwindow = QtWidgets.QMainWindow()
        self.setupUi(self.Mainwindow)
        self.Mainwindow.show()
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_chat = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_chat.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_chat.setObjectName("horizontalLayout_chat")
        self.verticalLayout_chat = QtWidgets.QVBoxLayout()
        self.verticalLayout_chat.setObjectName("verticalLayout_chat")
        self.textBrowser_chat = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.textBrowser_chat.setFont(font)
        self.textBrowser_chat.setObjectName("textBrowser_chat")
        self.verticalLayout_chat.addWidget(self.textBrowser_chat)
        self.label_chat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.label_chat.setFont(font)
        self.label_chat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_chat.setObjectName("label_chat")
        self.verticalLayout_chat.addWidget(self.label_chat)
        self.horizontalLayout_chat.addLayout(self.verticalLayout_chat)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_people = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_people.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_people.setObjectName("horizontalLayout_people")
        self.verticalLayout_people = QtWidgets.QVBoxLayout()
        self.verticalLayout_people.setObjectName("verticalLayout_people")
        self.textBrowser_people = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.textBrowser_people.setFont(font)
        self.textBrowser_people.setObjectName("textBrowser_people")
        self.verticalLayout_people.addWidget(self.textBrowser_people)
        self.label_people = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.label_people.setFont(font)
        self.label_people.setAlignment(QtCore.Qt.AlignCenter)
        self.label_people.setObjectName("label_people")
        self.verticalLayout_people.addWidget(self.label_people)
        self.horizontalLayout_people.addLayout(self.verticalLayout_people)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_message = QtWidgets.QHBoxLayout()
        self.horizontalLayout_message.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_message.setSpacing(4)
        self.horizontalLayout_message.setObjectName("horizontalLayout_message")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.textEdit.setFont(font)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_message.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(20, 25))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_message.addWidget(self.pushButton)
        self.horizontalLayout_message.setStretch(0, 8)
        self.horizontalLayout_message.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_message)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionmake_new_room = QtWidgets.QAction(MainWindow)
        self.actionmake_new_room.setObjectName("actionmake_new_room")
        self.actionconnect_room = QtWidgets.QAction(MainWindow)
        self.actionconnect_room.setObjectName("actionconnect_room")
        self.actionexit_room = QtWidgets.QAction(MainWindow)
        self.actionexit_room.setObjectName("actionexit_room")
        self.actiondelete_selected = QtWidgets.QAction(MainWindow)
        self.actiondelete_selected.setObjectName("actiondelete_selected")
        self.actiondelete_all = QtWidgets.QAction(MainWindow)
        self.actiondelete_all.setObjectName("actiondelete_all")
        self.menu.addAction(self.actionmake_new_room)
        self.menu.addAction(self.actionconnect_room)
        self.menu.addSeparator()
        self.menu.addAction(self.actionexit_room)
        self.menu_2.addAction(self.actiondelete_selected)
        self.menu_2.addAction(self.actiondelete_all)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        pass
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Connection"))
        self.pushButton.setText(_translate("MainWindow", "보내기"))
        self.label_chat.setText(_translate("MainWindow", "채팅 내용"))
        self.label_people.setText(_translate("MainWindow", "채팅방 참여자 목록"))
        self.menu.setTitle(_translate("MainWindow", "채팅방"))
        self.menu_2.setTitle(_translate("MainWindow", "채팅 옵션"))
        self.actionmake_new_room.setText(_translate("MainWindow", "채팅방 만들기"))
        self.actionconnect_room.setText(_translate("MainWindow", "채팅방 들어가기"))
        self.actionexit_room.setText(_translate("MainWindow", "채팅방 나가기"))
        self.actiondelete_selected.setText(_translate("MainWindow", "선택 채팅 기록 삭제"))
        self.actiondelete_all.setText(_translate("MainWindow", "모든 채팅 기록 삭제"))
        pass
    pass

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = Ui_MainWindow()
    sys.exit(app.exec_())
    pass
